name: publish

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Important for changelog
          filter: blob:none # We don't need all blobs

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          standalone: true

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - run: pnpm install

      - run: echo VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_ENV
      - run: pnpm version ${VERSION}

      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@8bfb7bf10268aed30bde8e34ecaeddb6c6149edd # v2.1.0
        with:
          args: --latest --strip all
          output: 'CHANGELOG.md'

      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          bodyFile: 'CHANGELOG.md'
          name: ${{ env.VERSION }}
          prerelease: ${{ contains(github.ref_name, '-') }}
