name: publish

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm version ${GITHUB_REF_NAME#v}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: ncipollo/release-action@v1.13.0
        with:
          generateReleaseNotes: true
