name: publish

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Important for changelog
          filter: blob:none # We don't need all blobs

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          standalone: true

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - run: pnpm install

      - run: echo VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_ENV
      - run: pnpm version ${VERSION}

      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@75599f745633e29f99bd9e14a30865b7d2fcbe84 # v1.5.0
        with:
          args: --latest --strip all
          output: 'CHANGELOG.md'

      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
        with:
          bodyFile: 'CHANGELOG.md'
          name: ${{ env.VERSION }}
          prerelease: ${{ contains(github.ref_name, '-') }}
